apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    {{- include "lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      automountServiceAccountToken: false
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $name, $value := .Values.worker.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: app-cache
              mountPath: /var/cache/app
      volumes:
        - name: app-cache
          emptyDir: {}
